apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
  labels:
    app: user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: phpmyadmin:5.2.1-apache
        env:
        - name: PMA_HOST
          valueFrom:
              configMapKeyRef:
                name: database-configmap
                key: user_database_url
        - name: PMA_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: db_user_name
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: db_user_password

---
apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  type: LoadBalancer
  selector:
    app: user-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-api-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-api
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70